AdmFinanceiraPessoalWeb/Controllers/ContasMesController.cs
using AdmFinanceiraPessoalCore.Domain.Controller;
using AdmFinanceiraPessoalCore.Domain.Model;
using AdmFinanceiraPessoalCore.Modulos;
using AdmFinanceiraPessoalCore.Modulos.Repositories;
using NHibernate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace AdmFinanceiraPessoalWeb.Controllers
{
    public class ContasMesController : Controller, IAdmFin
    {
        private readonly IContaMesRepository _contaMesRepository;

        private readonly IPagamentoContaMesRepository _pagamentoContaMesRepository;

        protected ISession _session;

        public ContasMesController(IContaMesRepository contaMesRepository, IPagamentoContaMesRepository pagamentoContaMesRepository)
        {
            _contaMesRepository = contaMesRepository;

            _pagamentoContaMesRepository = pagamentoContaMesRepository;
        }

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetViewData()
        {
            try
            {
                var date = DateTime.Now;

                var list = _contaMesRepository.FindPorMes(date);

                return Json(list);
            }
            catch (Exception ex)
            {
                return RetrieveError("Serviço indisponivel.");
            }
        }

        public JsonResult SalvarContaMes(ContaMes contaMes)
        {
            try
            {               
                if(contaMes.Id == 0)
                {
                    contaMes.Status = "Aberta";
                }
                _contaMesRepository.AddOrUpdate(contaMes);

                return Json(contaMes);
            }
            catch (Exception ex)
            {
                return RetrieveError("Serviço Indisponivel.");
            }
        }

        
        public JsonResult Pagar(PagamentoContaMes pagamento)
        {
            try
            {
                pagamento.Descricao = "Pagamento conta:  " + pagamento.IdContaMes.Descricao;

                _pagamentoContaMesRepository.AddOrUpdate(pagamento);

                _contaMesRepository.AddOrUpdate(ContaPaga(pagamento));

                return Json(pagamento);
            }
            catch (Exception ex)
            {
                return RetrieveError("Serviço indisponivel.");
            }
        }

        public ContaMes ContaPaga(PagamentoContaMes pagamento)
        {
            
            var conta = pagamento.IdContaMes;

            if(conta.Valor > pagamento.Valor)
            {
                conta.Status = "Parcialmente paga";
            } 
            else if (conta.Valor == pagamento.Valor )
            {
                conta.Status = "Paga";
            } 
            
            return conta;           
        }

        public JsonResult ExcluirConta(ContaMes contaMes)
        {
            try
            {
                _contaMesRepository.Remove(contaMes.Id);

                return Json(new { });
            }
            catch (Exception ex)
            {
                return RetrieveError("Serviço indisponivel.");
            }
        }        

        protected JsonResult RetrieveError(string msg)
        {
            Response.StatusCode = (int)HttpStatusCode.InternalServerError;

            return Json(new { message = msg }, "text/html");
        }
    }
}

AdmFinanceiraPessoalWeb/Controllers/HomeController.cs
using AdmFinanceiraPessoalCore.Domain.Controller;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdmFinanceiraPessoalWeb.Controllers
{
    public class HomeController : Controller, IAdmFin
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AdmFinanceiraPessoalWeb/Controllers/TarefaController.cs
using AdmFinanceiraPessoalCore.Domain.Controller;
using AdmFinanceiraPessoalCore.Domain.Model;
using AdmFinanceiraPessoalCore.Modulos;
using AdmFinanceiraPessoalCore.Modulos.Repositories;
using NHibernate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace AdmFinanceiraPessoalWeb.Controllers
{
    public class TarefaController : Controller, IAdmFin
    {
        private readonly ITarefaRepository _tarefaRepository;      

        protected ISession _session;

        public TarefaController(ITarefaRepository tarefaRepository)
        {
            _tarefaRepository = tarefaRepository;
        }

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetViewData()
        {
            try
            {
                var periodo = Periodo.SemanaAtual();

                var list = _tarefaRepository.FindSemanaAtual(periodo);

                return Json(list);
            }
            catch (Exception ex)
            {
                return RetrieveError("Serviço indisponivel.");
            }
        }

        public JsonResult SalvarTarefa(Tarefa tarefa)
        {
            try
            {
                if (string.IsNullOrEmpty(tarefa.Status))
                {
                    tarefa.Status = "Nova";
                }

                _tarefaRepository.AddOrUpdate(tarefa);

                return Json(tarefa);
            }
            catch (Exception ex)
            {
                return RetrieveError("Serviço Indisponivel.");
            }
        }

        public JsonResult ConcluirTarefa(Tarefa tarefa)
        {
            try
            {
                tarefa.Status = "Concluida";

                _tarefaRepository.AddOrUpdate(tarefa);

                return Json(tarefa);
            }
            catch
            {
                return RetrieveError("Serviço Indisponvel");
            }
        }

        protected JsonResult RetrieveError(string msg)
        {
            Response.StatusCode = (int)HttpStatusCode.InternalServerError;

            return Json(new { message = msg }, "text/html");
        }
    }
}

AdmFinanceiraPessoalWeb/Views/ContasMes/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div ng-app="IAdmFin" ng-controller="ContaController" ng-cloak>
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading" style="text-align:center">
                <h3 style="text-align:center"><b>{{viewdata.titulo}}</b></h3>
            </div>
            <button class="btn btn-info btn-sm" ng-click="modalCadastrarConta()" accesskey="C">Cadastrar Conta</button>

        </div>

        <div class="panel panel-default">
            <div class="panel-body">
                <table class="table table-striped table-hover table-sm">
                    <thead>
                        <tr>
                            <th class="col-lg-3">Descrição</th>
                            <th class="col-lg-1">Data Pagamento</th>
                            <th class="col-lg-1">Valor</th>
                            <th class="col-lg-1">Periodicidade</th>
                            <th class="col-lg-1">Status</th>
                            <th>Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr ng-repeat="item in viewdata.contas | orderBy:'DataPagamento'">
                            <td>{{item.Descricao}}</td>
                            <td class="col-lg-1">{{item.DataPagamento | dateFilter| date:"dd/MM/yyyy"}}</td>
                            <td class="col-lg-1">{{item.Valor}}</td>
                            <td class="col-lg-1">{{item.Periodicidade}}</td>
                            <td class="col-lg-1">{{item.Status}}</td>
                            <td class="col-lg-2">
                                <button type="button" class="btn btn-success btn-xs" ng-show="item.Status != 'Paga'" ng-click="modalCadastrarPagamento(item)">
                                    <span class="glyphicon glyphicon-usd">Pagar</span>
                                </button>
                                <button type="button" class="btn btn-primary btn-xs" ng-click="editarCon(item)">
                                    <span class="glyphicon glyphicon-pencil"></span>
                                </button>
                                <button type="button" class="btn btn-danger btn-xs" ng-click="excluirConta(item)">
                                    <span class="glyphicon glyphicon-remove"></span>
                                </button>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    @Html.Partial("_CadContaMes")
    @Html.Partial("_CadPagamentoMes")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/contaMes")
}

AdmFinanceiraPessoalWeb/Views/ContasMes/_CadContaMes.cshtml
@{
    ViewBag.Title = "_CadContaMes";
}

<div class="modal fade" id="formCadConta">
    <div class="modal-dialog">
        <div class="modal-content">
            <form name="cadConta" ng-validate="{}">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Cadastro de Contas do Mês</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="form-group col-sm-6 col-md-6 col-lg-6">
                            <label>Descrição</label>
                            <input type="text" class="form-control required" name="Descricao" ng-model="viewdata.conta.Descricao" />
                        </div>
                        <div class="form-group col-sm-6 col-md-6 col-lg-6">
                            <label>Valor</label>
                            <input type="number" step="0.01" class="form-control required" name="Valor" ng-model="viewdata.conta.Valor" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-sm-6 col-md-6 col-lg-6">
                            <label>Data de Pagamento</label>
                            <input type="date" class="form-control required" name="DataPagamento" ng-model="viewdata.conta.DataPagamento" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-sm-6 col-md-6 col-lg-6">
                            <label>Dono da conta</label>
                            <select placeholder="Selecione o dono da conta..." name="Comprador" id="Comprador" class="form-control" ng-model="viewdata.conta.Periodicidade">
                                <option value="">---Selecione---</option>
                                <option value="Unica">Unica</option>
                                <option value="Ocasional">Ocasional</option>
                                <option value="Mensal">Mensal</option>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-4 col-lg-3">
                            <button type="submit" class="btn btn-primary form-control" ng-click="validaForm(cadConta) && salvarConta()">Salvar</button>
                        </div>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>

AdmFinanceiraPessoalWeb/Views/ContasMes/_CadPagamentoMes.cshtml
@{
    ViewBag.Title = "_CadPagamentoMes";
}

<div class="modal fade" id="formCadPagamento">
    <div class="modal-dialog">
        <div class="modal-content">
            <form name="cadPagamento" ng-validate="{}">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Cadastro de Pagamento de {{viewdata.pagamento.IdContaMes.Descricao}}</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="form-group col-sm-6 col-md-6 col-lg-6">
                            <label>Valor</label>
                            <input type="number" step="0.05" class="form-control required" name="Valor" ng-model="viewdata.pagamento.Valor" />
                        </div>
                        <div class="form-group col-sm-6 col-md-6 col-lg-6">
                            <label>Pago Em:</label>
                            <input type="date" class="form-control required" name="DataRegPagamento" ng-model="viewdata.pagamento.DtPagamento" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-4 col-lg-3">
                            <button type="submit" class="btn btn-primary form-control" ng-click="validaForm(cadPagamento) && salvarPagamento()">Salvar</button>
                        </div>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>

AdmFinanceiraPessoalWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AdmFinanceiraPessoalWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AdmFinanceiraPessoalWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

AdmFinanceiraPessoalWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Contas do Mês", "Index", "ContasMes")</li>
                    <li>@Html.ActionLink("Tarefas", "Index", "Tarefa")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery-plugins")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")
    @Scripts.Render("~/bundles/chart")
    @RenderSection("scripts", required: false)
</body>
</html>

AdmFinanceiraPessoalWeb/Views/Tarefa/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div ng-app="IAdmFin" ng-controller="TarefaController" ng-cloak>
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading" style="text-align:center">
                <h3 style="text-align:center"><b>Tarefas</b></h3>
            </div>
            <button class="btn btn-info btn-sm" ng-click="modalCadastrarTarefa()" accesskey="C">Cadastrar Tarefa</button>
        </div>


            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table table-striped table-hover table-sm">
                        <thead>
                            <tr>
                                <th class="col-lg-3">Tarefa</th>
                                <th class="col-lg-1">Data final</th>
                                <th class="col-lg-1">Prioridade</th>
                                <th class="col-lg-2">Duração estimada</th>
                                <th class="col-lg-1">Status</th>
                                <th class="col-lg-2">Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr ng-repeat="item in viewdata.tarefas | orderBy:'DtFin'">
                                <td>{{item.NomeTarefa}}</td>
                                <td class="col-lg-1">{{item.DtFim | dateFilter| date:"dd/MM/yyyy"}}</td>
                                <td class="col-lg-1">{{item.Prioridade}}</td>
                                <td class="col-lg-2">{{item.DuracaoEstimada | dateFilter| date:"HH:mm"}}</td>
                                <td class="col-lg-1">{{item.Status}}</td>
                                <td class="col-lg-2">
                                    <button type="button" class="btn btn-success btn-xs" ng-show="item.Status != 'Paga'" ng-click="concluirTarefa(item)">
                                        <span class="glyphicon glyphicon-ok">Terminar</span>
                                    </button>
                                    <button type="button" class="btn btn-primary btn-xs" ng-click="editarTarefa(item)">
                                        <span class="glyphicon glyphicon-pencil"></span>
                                    </button>
                                    <button type="button" class="btn btn-danger btn-xs" ng-click="">
                                        <span class="glyphicon glyphicon-remove"></span>
                                    </button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        
    </div>
    @Html.Partial("_CadTarefa")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/tarefa")
}

AdmFinanceiraPessoalWeb/Views/Tarefa/_CadTarefa.cshtml
@{
    ViewBag.Title = "_CadTarefa";
}

<div class="modal fade" id="formCadTarefa">
    <div class="modal-dialog">
        <div class="modal-content">
            <form name="cadTarefa" ng-validate="{}">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Cadastro de Tarefa</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="form-group col-sm-6 col-md-6 col-lg-6">
                            <label>NomeTarefa</label>
                            <input type="text" class="form-control required" name="Descricao" ng-model="viewdata.tarefa.NomeTarefa" />
                        </div>
                        <div class="form-group col-sm-6 col-md-6 col-lg-6">
                            <label>Prazo final</label>
                            <input type="date" class="form-control required" name="DataPagamento" ng-model="viewdata.tarefa.DtFim" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-sm-6 col-md-6 col-lg-6">
                            <label>Prioridade</label>
                            <input type="number" class="form-control required" name="Valor" ng-model="viewdata.tarefa.Prioridade" />
                        </div>
                        <div class="form-group col-sm-6 col-md-6 col-lg-6">
                            <label>Duração</label>
                            <input type="time" class="form-control required" placeholder="HH:mm" name="Duracao" ng-model="viewdata.tarefa.DuracaoEstimada" />
                        </div>                        
                    </div>
                    <div class="row" ng-show="viewdata.tarefa.Status">
                        <div class="form-group col-sm-6 col-md-6 col-lg-6">
                            <label>Duração</label>
                            <select placeholder="Selecione o dono da conta..." name="Comprador" id="Comprador" class="form-control" ng-model="viewdata.tarefa.Status">
                                <option value="">---Selecione---</option>
                                <option selected value="Nova">Nova</option>
                                <option value="Concluida">Concluida</option>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-4 col-lg-3">
                            <button type="submit" class="btn btn-primary form-control" ng-click="validaForm(cadTarefa) && salvarTarefa()">Salvar</button>
                        </div>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>